name = "MomentGSE"
uuid = "71df4310-1531-11eb-256d-190d0a52716f"
authors = ["jwang <wangjie212@mails.ucas.ac.cn>"]
version = "0.1.0"

[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
