name = "QMBCertify"
uuid = "71df4310-1531-11eb-256d-190d0a52716f"
authors = ["Jie Wang <wangjie212@amss.ac.cn>"]
version = "0.3.4"

[deps]
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"

[compat]
Dualization = "0.7.1"
